from datetime import date

user_name = "Meyra CEBEL"
valid_user_name = "meyracebel@gmail.com"
valid_password = "pair.6.otomasyon"
invalid_password = "123456"
success_message = "• Giriş başarılı."
error_message = "Doldurulması zorunlu alan*"
chatbot_pleased_message = f"Memnun oldum {user_name}, Sana hangi konuda yardımcı olmamı istersin?"
choice_1 = "🤖 Tobeto Hakkında"
choice_2 = "💻 İstanbul Kodluyor Hakkında"
choice_1_message = "Bunları da merak ediyor olabilirsiniz. 👀"
choice_2_message = "Aşağıdaki konu başlıkları hakkında da yardımcı olabilirim. 😊"
social_media_add_message = "• Sosyal medya adresiniz başarıyla eklendi."
social_media_update_message = "• Sosyal medya adresiniz başarıyla güncellendi."
field_error_message = "Doldurulması zorunlu alan*"
emoji = "😋"
lesson_name = "Deneme"
instructor_name = "Gürkan İlişen"
months = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"]
year = date.today().year
survey_message = "Atanmış herhangi bir anketiniz bulunmamaktadır"
lesson_name = "Dr. Ecmel Ayral'dan Hoşgeldin Mesajı"
favorite_add_message = "Favorilere ekleme işlemin başarıyla gerçekleşti."

loginURL = "https://tobeto.com/giris"
certificatesURL = "https://tobeto.com/profilim/profilimi-duzenle/sertifikalarim"
certificateName = "certificate1"
certificateYear = "2024"
certificatePDF = "C:\\Users\\Miray\\Downloads\\TobetoTest-3A\\Python_Essentials_1_Badge20240523-8-9tn7xa.pdf"
invalidCertificate = "C:\\Users\\Miray\\Downloads\\TobetoTest-3A\\Jira.csv"
invalid_certificate_message = "Sadece image/jpeg, image/png, application/pdf yükleyebilirsiniz"
certificate_delete_message = "• Dosya kaldırma işlemi başarılı."